;;; gameoflife-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gameoflife.el

(autoload 'gameoflife-animate "gameoflife" "\
Animate Conway's Game of Life in all windows in all frames.

COUNT determines the number of generations to run.  When omitted,
the animation runs for ever.

When a user input is available, this function returns.

The content of the windows of the frame are used as the seed of
the animation.

(fn &optional COUNT)" t)
(defvar gameoflife-screensaver-mode nil "\
Non-nil if Gameoflife-Screensaver mode is enabled.
See the `gameoflife-screensaver-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `gameoflife-screensaver-mode'.")
(custom-autoload 'gameoflife-screensaver-mode "gameoflife" nil)
(autoload 'gameoflife-screensaver-mode "gameoflife" "\
Run Conway's Game of Life when Emacs has been idle for a while.

This is a global minor mode.  If called interactively, toggle the
`Gameoflife-Screensaver mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='gameoflife-screensaver-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "gameoflife" '("gameoflife-"))

;;; End of scraped data

(provide 'gameoflife-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gameoflife-autoloads.el ends here
